### ISSUE TITLE
Need Of Another release!

### ISSUE THREAD

**Issue by eagleanurag** [SeppPenner/PdfPasswordRemover#1]
Please Release  executable  file in next Version.....

**Comment by SeppPenner** [comment]
There is a setup file located under https://github.com/SeppPenner/PdfPasswordRemover/tree/master/Setup. I will try to add a new release with the file included, soon.

**Comment by eagleanurag** [comment]
> 
> 
> There is a setup file located under https://github.com/SeppPenner/PdfPasswordRemover/tree/master/Setup. I will try to add a new release with the file included, soon.

Wow! That's Nice,

Have a Happy Time 🌞

**Comment by eagleanurag** [comment]
> There is a setup file located under https://github.com/SeppPenner/PdfPasswordRemover/tree/master/Setup. I will try to add a new release with the file included, soon.



I tried it in Windows but it is crashing all the time 

is it only decrypting easy password based pdf?

**Comment by SeppPenner** [comment]
> I tried it in Windows but it is crashing all the time

This shouldn't happen. I will have to check.

> is it only decrypting easy password based pdf?

Well, the more complex the password, the longer it will take. The program tries to brute force the passwords if you don't specifiy one.

**Comment by eagleanurag** [comment]
Yes that is the main reason


![password_time_and_length](https://user-images.githubusercontent.com/22770735/90388760-f6057580-e0a5-11ea-8b20-76dd44a0c348.jpg)
