### ISSUE TITLE
Action (Unable to test This repo)

### ISSUE THREAD

**Issue by eagleanurag** [SeppPenner/PdfPasswordRemover#2]
![Screenshot (190)](https://user-images.githubusercontent.com/22770735/90551515-153bfa00-e1af-11ea-8ce0-83602aa0eb62.png)

**Comment by SeppPenner** [comment]
Yes, I know. Snyk doesn't have this feature yet. Related issue from the snyk team: https://github.com/snyk/snyk/issues/489

**Comment by eagleanurag** [comment]
It means the Problem is from Root, Got it!
