### ISSUE TITLE
would not run.

### ISSUE THREAD

**Issue by KNelTech** [SeppPenner/PdfPasswordRemover#3]
using the install .exe I first installed then tried to run the program. nothing popped up and no process was started. legion 5i, i7 win 11 pro 10.0.22000 build 22000. uninstalled.

**Comment by SeppPenner** [comment]
There might be something missing in the installer, need to check it.

**Comment by SeppPenner** [comment]
I can't confirm the bug... (Still, I don't have Windows 11 yet). Can you give the new version a try, please?
